routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", "BlogController@index")->name("blog.index");

Route::group(["prefix" => "articles"], function() {
    Route::get("/categories/{category}", "BlogController@post_category_list")->name("blog.post.category_list");
    Route::get("/tags/{tag}", "BlogController@post_tag_list")->name("blog.post.post_tag_list");
    Route::get("/search", "BlogController@search")->name("blog.post.search");
    Route::get("/{post}/{slug}", "BlogController@show")->name("blog.show");
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::group(["prefix" => "admin", "middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name("admin.dashboard");
    
    Route::resource("category", "CategoryController", ["as" => "admin"])->except(["show"]);
    Route::resource("tag", "TagController", ["as" => "admin"])->except(["show"]);
    Route::resource("user", "UserController", ["as" => "admin"])->except(["show"]);
    Route::get("/post/trashed", "PostController@trashed_posts")->name("admin.post.trashed_posts");
    Route::get("/post/trashed/restore/{post}", "PostController@restore")->name("admin.post.restore");
    Route::delete("/post/trashed/{post}", "PostController@soft_delete")->name("admin.post.soft_delete");
    Route::resource("post", "PostController", ["as" => "admin"]);
});

app/Post.php
<?php

namespace App;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = ["category_id", "user_id", "title", "content", "image", "slug"];

    public function category() {
        return $this->belongsTo(Category::class);
    }

    public function setSlugAttribute($value) {
        $this->attributes["slug"] = Str::slug($value);
    }

    public function tags() {
        return $this->belongsToMany(Tag::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Post;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->user_role) {
            $posts = Post::with(["category", "tags"])->orderBy("created_at", "DESC")->paginate(10);
        } else {
            $posts = Post::with(["category", "tags"])->where("user_id", Auth::user()->id)->orderBy("created_at", "DESC")->paginate(10);
        }

        return view("admin.post.index", compact("posts"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::orderBy("created_at", "DESC")->get();
        $categories = Category::orderBy("created_at", "DESC")->get();

        return view("admin.post.create", compact("tags", "categories"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "category_id" => "required|integer|exists:categories,id",
            "title" => "required|string",
            "content" => "required",
            "image" => "required|image|mimes:png,jpeg,jpg"
        ]);

        if ($request->hasFile("image")) {
            $file = $request->file("image");
            $filename = time() . "." . $file->getClientOriginalExtension();
            
            $file->storeAs("public/posts", $filename);

            $post = Post::create([
                "category_id" => $request->category_id,
                "user_id" => Auth::id(),
                "title" => $request->title,
                "content" => $request->content,
                "image" => $filename,
                "slug" => $request->title
            ]);

            $post->category()->attach($request->category_id);
            $post->tags()->attach($request->tags);
        }

        return redirect(route("admin.post.index"))->with(["success" => "Post created successfully!"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $tags = Tag::orderBy("created_at", "DESC")->get();
        $categories = Category::orderBy("created_at", "DESC")->get();

        return view("admin.post.edit", compact("post", "tags", "categories"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $this->validate($request, [
            "category_id" => "required|integer|exists:categories,id",
            "title" => "required|string",
            "content" => "required",
            "image" => "nullable|image|mimes:png,jpeg,jpg"
        ]);
        
        $request->request->add(["slug" => $request->title]);
        
        $filename = $post->image;

        if ($request->hasFile("image")) {
            $file = $request->file("image");
            $filename = time() . "." . $file->getClientOriginalExtension();
            
            $file->storeAs("public/posts", $filename);

            File::delete(storage_path('app/public/posts/' . $post->image));
        }

        $post->update([
            "category_id" => $request->category_id,
            "title" => $request->title,
            "content" => $request->content,
            "image" => $filename,
            "slug" => $request->title
        ]);

        $post->category()->detach();
        $post->tags()->detach();

        $post->category()->attach($request->category_id);
        $post->tags()->attach($request->tags);

        return redirect(route("admin.post.index"))->with(["success" => "Post created successfully!"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::withTrashed()->where("id", $id)->first();

        File::delete(storage_path('app/public/posts/' . $post->image));

        $post->forceDelete();

        return redirect()->back()->with(["success" => "Post deleted successfully!"]);
    }

    public function soft_delete(Post $post)
    {
        $post->delete();

        return redirect(route("admin.post.index"))->with(["success" => "Post deleted successfully!"]);
    }

    public function trashed_posts() {
        $posts = Post::onlyTrashed()->paginate(10);

        return view("admin.post.trashed", compact("posts"));
    }

    public function restore($id) {
        $post = Post::withTrashed()->where("id", $id)->first();
        $post->restore();

        return redirect()->back()->with(["success" => "Post restored successfully!"]);
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin Dashboard</title>
@endsection

@section('css-libraries')
<link rel="stylesheet" href="{{ asset('assets/admin/modules/select2/dist/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/modules/jquery-selectric/selectric.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/modules/summernote/summernote-bs4.css') }}">
@endsection

@section('content-title')
<h1>Add Post</h1>

<div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Add Post</div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <h4>Add Post</h4>
        </div>
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col">
                <form action="{{ route('admin.post.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" name="title" class="form-control" placeholder="Enter post title" required>

                        <p class="text-danger">{{ $errors->first("title") }}</p>
                    </div>

                    <div class="form-group">
                        <label>Category</label>

                        <select name="category_id" class="form-control" required>
                            @foreach ($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>

                        <p class="text-danger">{{ $errors->first("category_id") }}</p>
                    </div>

                    <div class="form-group">
                        <label>Tags</label>
                        <select class="form-control select2" multiple="" name="tags[]">
                            @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Content</label>
                        <div>
                            <textarea name="content" class="summernote" placeholder="Enter post content"
                                required></textarea>

                            <p class="text-danger">{{ $errors->first("content") }}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="image">Image</label>

                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="image" class="custom-file-input" id="image" required />

                                <label class="custom-file-label" for="image">Choose image</label>
                            </div>
                        </div>

                        <p class="text-danger">{{ $errors->first("image") }}</p>
                    </div>

                    <div class="card-footer text-right">
                        <button class="btn btn-primary mr-1" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js-libraries')
<script src="{{ asset('assets/admin/modules/select2/dist/js/select2.full.min.js') }}"></script>
<script src="{{ asset('assets/admin/modules/jquery-selectric/jquery.selectric.min.js') }}"></script>
<script src="{{ asset('assets/admin/modules/summernote/summernote-bs4.js') }}"></script>
@endsection

@section('custom-js')
<script>
    $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>
@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin Dashboard</title>
@endsection

@section('css-libraries')
<link rel="stylesheet" href="{{ asset('assets/admin/modules/select2/dist/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/modules/jquery-selectric/selectric.css') }}">
<link rel="stylesheet" href="{{ asset('assets/admin/modules/summernote/summernote-bs4.css') }}">
@endsection

@section('content-title')
<h1>Edit Post</h1>

<div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Edit Post</div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <h4>Edit Post</h4>
        </div>
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col">
                <form action="{{ route('admin.post.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method("PUT")

                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" name="title" class="form-control" placeholder="Enter post title"
                            value="{{ $post->title }}" required>

                        <p class="text-danger">{{ $errors->first("title") }}</p>
                    </div>

                    <div class="form-group">
                        <label>Category</label>

                        <select name="category_id" class="form-control" required>
                            @foreach ($categories as $category)
                            <option value="{{ $category->id }}"
                                {{ $post->category_id == $category->id ? 'selected' : '' }}>
                                {{ $category->name }}</option>
                            @endforeach
                        </select>

                        <p class="text-danger">{{ $errors->first("category_id") }}</p>
                    </div>

                    <div class="form-group">
                        <label>Tags</label>
                        <select class="form-control select2" multiple="" name="tags[]">
                            @foreach ($tags as $tag)
                            <option value="{{ $tag->id }}" @foreach ($post->tags as $postTag)
                                {{ $postTag->id == $tag->id ? 'selected' : '' }}
                                @endforeach>{{ $tag->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Content</label>
                        <div>
                            <textarea name="content" class="summernote" placeholder="Enter post content"
                                value="{{ $post->content }}" required>{{ $post->content }}</textarea>

                            <p class="text-danger">{{ $errors->first("content") }}</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="image">Image</label>

                        <div class="mb-2">
                            <img src="{{ asset('storage/posts/' . $post->image) }}" width="500px" class="img-fluid">
                        </div>

                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="image" class="custom-file-input" id="image" />

                                <label class="custom-file-label" for="image">Choose image</label>
                            </div>
                        </div>

                        <p><b>Leave it empty if you doesn't want to update the image.</b></p>

                        <p class="text-danger">{{ $errors->first("image") }}</p>
                    </div>

                    <div class="card-footer text-right">
                        <button class="btn btn-primary mr-1" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js-libraries')
<script src="{{ asset('assets/admin/modules/select2/dist/js/select2.full.min.js') }}"></script>
<script src="{{ asset('assets/admin/modules/jquery-selectric/jquery.selectric.min.js') }}"></script>
<script src="{{ asset('assets/admin/modules/summernote/summernote-bs4.js') }}"></script>
@endsection

@section('custom-js')
<script>
    $(".custom-file-input").on("change", function () {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>
@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin Dashboard</title>
@endsection

@section('content-title')
<h1>List Post</h1>

<div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
    <div class="breadcrumb-item">List Post</div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <a href="{{ route('admin.post.create') }}" class="btn btn-icon icon-left btn-primary"><i
                    class="far fa-edit"></i> Add Post</a>
        </div>
    </div>

    <div class="card-body">

        @if (session("success"))
        <div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
                <button class="close" data-dismiss="alert">
                    <span>×</span>
                </button>

                {{ session("success") }}
            </div>
        </div>
        @endif

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Author</th>
                    <th scope="col">Image</th>
                    <th scope="col">Title</th>
                    <th scope="col">Tags</th>
                    <th scope="col">Category</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($posts as $post)
                <tr>
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>{{ $post->user->name }}</td>
                    <td><img class="rounded" width="50px" src="{{ asset('storage/posts/' . $post->image) }}"
                            alt="Image">
                    </td>
                    <td>{{ Str::limit($post->title, 15) }}</td>
                    <td>
                        <ul>
                            @foreach ($post->tags as $tag)
                            <li style="list-style: none"><span class="badge badge-primary">{{ $tag->name }}</span></li>
                            @endforeach
                        </ul>
                    </td>
                    <td>{{ Str::limit($post->category->name, 15) }}</td>
                    <td>
                        <form action="{{ route('admin.post.soft_delete', $post->id) }}" method="POST">
                            @csrf
                            @method("DELETE")

                            <a href="{{ route('admin.post.edit', $post->id) }}" class="btn btn-warning btn-sm"><i
                                    class="far fa-edit"></i> Edit</a>

                            <button type="submit" id="swal-6" class="btn btn-danger btn-sm"><i class="fas fa-times"></i>
                                Delete</button>
                        </form>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" class="text-center">Post is empty.</td>
                </tr>
                @endforelse
            </tbody>
        </table>

        <div class="row float-right">
            <div class="col">
                {{ $posts->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/post/trashed.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin Dashboard</title>
@endsection

@section('content-title')
<h1>List Trashed Post</h1>

<div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
    <div class="breadcrumb-item">List Trashed Post</div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-body">

        @if (session("success"))
        <div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
                <button class="close" data-dismiss="alert">
                    <span>×</span>
                </button>

                {{ session("success") }}
            </div>
        </div>
        @endif

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Image</th>
                    <th scope="col">Title</th>
                    <th scope="col">Tags</th>
                    <th scope="col">Category</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($posts as $post)
                <tr>
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td><img class="rounded" width="100px" src="{{ asset('storage/posts/' . $post->image) }}"
                            alt="Image">
                    </td>
                    <td>{{ Str::limit($post->title, 15) }}</td>
                    <td>
                        <ul>
                            @foreach ($post->tags as $tag)
                            <li style="list-style: none"><span class="badge badge-primary">{{ $tag->name }}</span></li>
                            @endforeach
                        </ul>
                    </td>
                    <td>{{ Str::limit($post->category->name, 15) }}</td>
                    <td>
                        <form action="{{ route('admin.post.destroy', $post->id) }}" method="POST">
                            @csrf
                            @method("DELETE")

                            <a href="{{ route('admin.post.restore', $post->id) }}" class="btn btn-primary btn-sm"><i
                                    class="far fa-edit"></i> Restore</a>

                            <button type="submit" id="swal-6" class="btn btn-danger btn-sm"><i class="fas fa-times"></i>
                                Delete</button>
                        </form>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" class="text-center">Post is empty.</td>
                </tr>
                @endforelse
            </tbody>
        </table>

        <div class="row float-right">
            <div class="col">
                {{ $posts->links() }}
            </div>
        </div>
    </div>
</div>
@endsection