routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", "BlogController@index")->name("blog.index");

Route::group(["prefix" => "articles"], function() {
    Route::get("/categories/{category}", "BlogController@post_category_list")->name("blog.post.category_list");
    Route::get("/tags/{tag}", "BlogController@post_tag_list")->name("blog.post.post_tag_list");
    Route::get("/search", "BlogController@search")->name("blog.post.search");
    Route::get("/{post}/{slug}", "BlogController@show")->name("blog.show");
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::group(["prefix" => "admin", "middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name("admin.dashboard");
    
    Route::resource("category", "CategoryController", ["as" => "admin"])->except(["show"]);
    Route::resource("tag", "TagController", ["as" => "admin"])->except(["show"]);
    Route::resource("user", "UserController", ["as" => "admin"])->except(["show"]);
    Route::get("/post/trashed", "PostController@trashed_posts")->name("admin.post.trashed_posts");
    Route::get("/post/trashed/restore/{post}", "PostController@restore")->name("admin.post.restore");
    Route::delete("/post/trashed/{post}", "PostController@soft_delete")->name("admin.post.soft_delete");
    Route::resource("post", "PostController", ["as" => "admin"]);
});

app/Tag.php
<?php

namespace App;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ["name", "slug"];

    public function setSlugAttribute($value) {
        $this->attributes["slug"] = Str::slug($value);
    }

    public function posts() {
        return $this->belongsToMany(Post::class);
    }

    public function getRouteKeyName() {
        return "slug";
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::orderBy("created_at", "DESC")->paginate(10);

        return view("admin.tag.index", compact("tags"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.tag.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required|string|unique:tags,slug|max:30"
        ]);

        $request->request->add(["slug" => $request->name]);

        $tag = Tag::create($request->except("_token"));

        return redirect(route("admin.tag.index"))->with(["success" => "Tag created successfully!"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view("admin.tag.edit", compact("tag"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        $this->validate($request, [
            "name" => "required|string|max:30|unique:tags,slug," . $tag->id
        ]);

        $request->request->add(["slug" => $request->name]);

        $tag->update($request->except("_token"));

        return redirect(route("admin.tag.index"))->with(["success" => "Tag updated successfully!"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        return redirect(route("admin.tag.index"))->with(["success" => "Tag deleted successfully!"]);
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin Dashboard</title>
@endsection

@section('content-title')
<h1>Add Tag</h1>

<div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Add Tag</div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <h4>Add Tag</h4>
        </div>
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col">
                <form action="{{ route('admin.tag.store') }}" method="POST">
                    @csrf

                    <div class="form-group">
                        <label>Tag Name</label>
                        <input type="text" name="name" class="form-control" placeholder="Enter tag name" required>

                        <p class="text-danger">{{ $errors->first("name") }}</p>
                    </div>

                    <div class="card-footer text-right">
                        <button class="btn btn-primary mr-1" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin Dashboard</title>
@endsection

@section('content-title')
<h1>Edit Tag</h1>

<div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Edit Tag</div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <h4>Edit Tag</h4>
        </div>
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col">
                <form action="{{ route('admin.tag.update', $tag->id) }}" method="POST">
                    @csrf
                    @method("PUT")

                    <div class="form-group">
                        <label>Tag Name</label>
                        <input type="text" name="name" class="form-control" placeholder="Enter tag name"
                            value="{{ $tag->name }}" required>

                        <p class="text-danger">{{ $errors->first("name") }}</p>
                    </div>

                    <div class="card-footer text-right">
                        <button class="btn btn-primary mr-1" type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.admin')

@section('title')
<title>Admin Dashboard</title>
@endsection

@section('content-title')
<h1>List Tag</h1>

<div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Dashboard</a></div>
    <div class="breadcrumb-item">List Tag</div>
</div>
@endsection

@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <a href="{{ route('admin.tag.create') }}" class="btn btn-icon icon-left btn-primary"><i
                    class="far fa-edit"></i> Add Tag</a>
        </div>
    </div>

    <div class="card-body">

        @if (session("success"))
        <div class="alert alert-success alert-dismissible show fade">
            <div class="alert-body">
                <button class="close" data-dismiss="alert">
                    <span>×</span>
                </button>

                {{ session("success") }}
            </div>
        </div>
        @endif

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Updated At</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>

            <tbody>
                @forelse ($tags as $tag)
                <tr>
                    <th scope="row">{{ $loop->iteration }}</th>
                    <td>{{ $tag->name }}</td>
                    <td>{{ $tag->updated_at->format("d-m-Y") }}</td>
                    <td>
                        <form action="{{ route('admin.tag.destroy', $tag->id) }}" method="POST">
                            @csrf
                            @method("DELETE")

                            <a href="{{ route('admin.tag.edit', $tag->id) }}" class="btn btn-warning btn-sm"><i
                                    class="far fa-edit"></i> Edit</a>

                            <button type="submit" id="swal-6" class="btn btn-danger btn-sm"><i class="fas fa-times"></i>
                                Delete</button>
                        </form>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="text-center">Tag is empty.</td>
                </tr>
                @endforelse
            </tbody>
        </table>

        <div class="row float-right">
            <div class="col">
                {{ $tags->links() }}
            </div>
        </div>
    </div>
</div>
@endsection