routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", "BlogController@index")->name("blog.index");

Route::group(["prefix" => "articles"], function() {
    Route::get("/categories/{category}", "BlogController@post_category_list")->name("blog.post.category_list");
    Route::get("/tags/{tag}", "BlogController@post_tag_list")->name("blog.post.post_tag_list");
    Route::get("/search", "BlogController@search")->name("blog.post.search");
    Route::get("/{post}/{slug}", "BlogController@show")->name("blog.show");
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::group(["prefix" => "admin", "middleware" => "auth"], function() {
    Route::get('/home', 'HomeController@index')->name("admin.dashboard");
    
    Route::resource("category", "CategoryController", ["as" => "admin"])->except(["show"]);
    Route::resource("tag", "TagController", ["as" => "admin"])->except(["show"]);
    Route::resource("user", "UserController", ["as" => "admin"])->except(["show"]);
    Route::get("/post/trashed", "PostController@trashed_posts")->name("admin.post.trashed_posts");
    Route::get("/post/trashed/restore/{post}", "PostController@restore")->name("admin.post.restore");
    Route::delete("/post/trashed/{post}", "PostController@soft_delete")->name("admin.post.soft_delete");
    Route::resource("post", "PostController", ["as" => "admin"]);
});

resources/views/layouts/admin/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad
            Nauval Azhar</a>
    </div>
    <div class="footer-right">
    </div>
</footer>

resources/views/layouts/admin/navbar.blade.php
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i
                        class="fas fa-search"></i></a></li>
        </ul>

        <div class="search-element">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">

            <button class="btn" type="submit"><i class="fas fa-search"></i></button>

            <div class="search-backdrop"></div>
        </div>
    </form>

    <ul class="navbar-nav navbar-right">
        <li class="dropdown"><a href="#" data-toggle="dropdown"
                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('assets/admin/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">{{ Auth::user()->name }}</div>
            </a>

            <div class="dropdown-menu dropdown-menu-right">
                <a href="features-profile.html" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>

                <a class="dropdown-item has-icon text-danger" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/admin/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{ route('admin.dashboard') }}">Admin Dashboard</a>
        </div>

        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('admin.dashboard') }}">AD</a>
        </div>

        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>

            <li class="dropdown">
                <a href="{{ route('admin.dashboard') }}" class="nav-link"><i
                        class="fas fa-fire"></i><span>Dashboard</span></a>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="far fa-clipboard"></i><span>Category</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('admin.category.index') }}">List Category</a></li>
                    <li><a class="nav-link" href="{{ route('admin.category.create') }}">Add Category</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="far fa-bookmark"></i><span>Tag</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('admin.tag.index') }}">List Tag</a></li>
                    <li><a class="nav-link" href="{{ route('admin.tag.create') }}">Add Tag</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-book-open"></i><span>Post</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('admin.post.index') }}">List Post</a></li>
                    <li><a class="nav-link" href="{{ route('admin.post.create') }}">Add Post</a></li>
                    <li><a class="nav-link" href="{{ route('admin.post.trashed_posts') }}">Trashed Posts</a></li>
                </ul>
            </li>

            @if (Auth::user()->user_role)
            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-user"></i><span>List User</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('admin.user.index') }}">List User</a></li>
                </ul>
            </li>
            @endif
        </ul>
    </aside>
</div>